import type { Reel } from "@/types/reel";

export const reels: Reel[] = [
  {
    id: "landscape-demo",
    authorId: "mock-landscape",
    author: "minh.thanh.tech",
    avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=160",
    caption:
      "Video ngang 16:9 có âm thanh để kiểm tra chế độ cover trên màn hình dọc.",
    comments: "215",
    hashtags: "#Technology  #Landscape",
    isAuthorVerified: true,
    isFollowing: false,
    isMine: false,
    isReacted: false,
    isSaved: false,
    reactionCount: 5200,
    reactionType: 0,
    saveCount: 0,
    shareCount: 0,
    thumbnailUrl: "",
    likes: "5.2k",
    sourceSize: "16:9 + audio",
    videoUrl: "https://media.w3.org/2010/05/bunny/trailer.mp4",
  },
  {
    id: "vertical-demo",
    authorId: "mock-vertical",
    author: "linh.di.day",
    avatar: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=160",
    caption:
      "Video dọc toàn màn hình, phù hợp với trải nghiệm video ngắn trên điện thoại.",
    comments: "486",
    hashtags: "#City  #VerticalVideo",
    isAuthorVerified: false,
    isFollowing: true,
    isMine: false,
    isReacted: false,
    isSaved: false,
    reactionCount: 12800,
    reactionType: 0,
    saveCount: 0,
    shareCount: 0,
    thumbnailUrl: "",
    likes: "12.8k",
    sourceSize: "9:16",
    videoUrl: "https://cdn.truefilesize.com/mp4/sample-portrait.mp4",
  },
  {
    id: "wide-demo",
    authorId: "mock-wide",
    author: "coffee.with.me",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=160",
    caption: "Nguồn video ngang để kiểm tra crop và căn giữa nội dung.",
    comments: "302",
    hashtags: "#Coffee  #WideVideo",
    isAuthorVerified: false,
    isFollowing: false,
    isMine: false,
    isReacted: false,
    isSaved: false,
    reactionCount: 8600,
    reactionType: 0,
    saveCount: 0,
    shareCount: 0,
    thumbnailUrl: "",
    likes: "8.6k",
    sourceSize: "16:9 trailer",
    videoUrl: "https://media.w3.org/2010/05/sintel/trailer.mp4",
  },
  {
    id: "square-demo",
    authorId: "mock-square",
    author: "huy.explore",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160",
    caption: "Video vuông để kiểm tra hiển thị nhiều tỷ lệ trong cùng luồng Reels.",
    comments: "913",
    hashtags: "#Travel  #SquareVideo",
    isAuthorVerified: false,
    isFollowing: false,
    isMine: false,
    isReacted: false,
    isSaved: false,
    reactionCount: 21400,
    reactionType: 0,
    saveCount: 0,
    shareCount: 0,
    thumbnailUrl: "",
    likes: "21.4k",
    sourceSize: "1:1",
    videoUrl: "https://cdn.truefilesize.com/mp4/sample-square.mp4",
  },
];
