import { Ionicons } from "@expo/vector-icons";
import { router, useFocusEffect, useLocalSearchParams } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { AdvertisementRequestError, cancelAdvertisement, getAdvertisement, pauseAdvertisement, resumeAdvertisement, submitAdvertisement } from "@/services/advertisement.service";
import { showAppToast } from "@/components/common/app-toast";
import { spacing, type ThemeColors, useTheme } from "@/theme";
import { AdvertisementStatus, type Advertisement } from "@/types/advertisement";
import { advertisementCtaLabel, advertisementStatusLabel } from "@/utils/advertisement-format";
import { formatVnd } from "@/utils/wallet-format";

export function AdvertisementDetailScreen() {
  const { id, submitted } = useLocalSearchParams<{ id: string; submitted?: string }>();
  const { theme } = useTheme();
  const styles = useMemo(() => createStyles(theme.colors), [theme.colors]);
  const [advertisement, setAdvertisement] = useState<Advertisement | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [cancelConfirmVisible, setCancelConfirmVisible] = useState(false);
  const load = useCallback(async () => { try { setAdvertisement(await getAdvertisement(id)); } catch (error) { showAppToast({ message: error instanceof Error ? error.message : "Không thể tải quảng cáo. Vui lòng thử lại.", type: "error" }); } finally { setLoading(false); } }, [id]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const mutate = async (action: () => Promise<Advertisement>) => { setBusy(true); try { setAdvertisement(await action()); } catch (error) { showAppToast({ message: error instanceof AdvertisementRequestError && error.code === "INSUFFICIENT_WALLET_BALANCE" ? "Số dư Ví ANKT không đủ để chạy quảng cáo." : error instanceof Error ? error.message : "Không thể cập nhật. Vui lòng thử lại.", type: "error" }); } finally { setBusy(false); } };
  if (loading || !advertisement) return <SafeAreaView style={styles.center}><ActivityIndicator color={theme.colors.primary} /></SafeAreaView>;
  const canPause = advertisement.status === AdvertisementStatus.Active;
  const canSubmit = advertisement.status === AdvertisementStatus.Draft;
  const canResume = advertisement.status === AdvertisementStatus.Paused;
  const canCancel = [AdvertisementStatus.Draft, AdvertisementStatus.Pending, AdvertisementStatus.Approved, AdvertisementStatus.Active, AdvertisementStatus.Paused].includes(advertisement.status);
  return <SafeAreaView edges={["top"]} style={styles.screen}><View style={styles.header}><Pressable accessibilityLabel="Quay lại" onPress={() => router.canGoBack() ? router.back() : router.replace("/advertisements")} style={styles.icon}><Ionicons color={theme.colors.text} name="arrow-back" size={22} /></Pressable><View style={styles.headerCopy}><Text style={styles.title}>Chi tiết quảng cáo</Text><Text style={styles.subtitle}>{advertisementStatusLabel(advertisement.status)}</Text></View></View><ScrollView contentContainerStyle={styles.content}>
    {submitted === "1" && advertisement.status === AdvertisementStatus.Pending ? <View style={styles.successNotice}><Text style={styles.successTitle}>✓ Đã gửi xét duyệt</Text><Text style={styles.successCopy}>Quảng cáo của bạn đã được gửi và đang chờ xét duyệt.</Text></View> : null}
    <View style={styles.hero}><Text style={styles.heroLabel}>Tổng ngân sách</Text><Text style={styles.heroValue}>{formatVnd(advertisement.totalBudget)}</Text><View style={styles.progressTrack}><View style={[styles.progress, { width: `${Math.min(100, advertisement.spentAmount * 100 / advertisement.totalBudget)}%` }]} /></View><View style={styles.heroFooter}><Text style={styles.muted}>Đã chi {formatVnd(advertisement.spentAmount)}</Text><Text style={styles.muted}>Còn giữ {formatVnd(advertisement.reservedAmount)}</Text></View></View>
    <View style={styles.metricGrid}><Metric icon="eye-outline" label="Hiển thị" value={String(advertisement.impressions)} /><Metric icon="hand-left-outline" label="Lượt nhấp" value={String(advertisement.clicks)} /><Metric icon="analytics-outline" label="CTR" value={`${advertisement.clickThroughRate}%`} /></View>
    <View style={styles.card}><Row label="Nội dung" value={advertisement.content.article?.title || advertisement.content.content || "Nội dung quảng cáo"} /><Row label="CTA" value={advertisementCtaLabel(advertisement.ctaType)} />{advertisement.dailyBudget ? <Row label="Ngân sách/ngày" value={formatVnd(advertisement.dailyBudget)} /> : null}<Row label="Bắt đầu" value={new Date(advertisement.startAt).toLocaleString("vi-VN")} /><Row label="Kết thúc" value={new Date(advertisement.endAt).toLocaleString("vi-VN")} />{advertisement.reviewReason ? <Row label="Lý do kiểm duyệt" value={advertisement.reviewReason} /> : null}</View>
    {(canSubmit || canPause || canResume || canCancel) ? <View style={styles.actions}>{canSubmit ? <Action disabled={busy} icon="send-outline" label="Gửi xét duyệt" onPress={() => void mutate(() => submitAdvertisement(id))} /> : null}{canPause ? <Action disabled={busy} icon="pause" label="Tạm dừng" onPress={() => void mutate(() => pauseAdvertisement(id))} /> : null}{canResume ? <Action disabled={busy} icon="play" label="Tiếp tục" onPress={() => void mutate(() => resumeAdvertisement(id))} /> : null}{canCancel ? <Action danger disabled={busy} icon="close-circle-outline" label="Hủy quảng cáo" onPress={() => setCancelConfirmVisible(true)} /> : null}</View> : null}
  </ScrollView><Modal animationType="fade" onRequestClose={() => setCancelConfirmVisible(false)} transparent visible={cancelConfirmVisible}><View style={styles.confirmBackdrop}><View style={styles.confirmCard}><Text style={styles.title}>Hủy quảng cáo?</Text><Text style={styles.confirmCopy}>Phần ngân sách chưa sử dụng sẽ được hoàn về số dư khả dụng.</Text><View style={styles.confirmActions}><Action disabled={busy} icon="close" label="Không" onPress={() => setCancelConfirmVisible(false)} /><Action danger disabled={busy} icon="close-circle-outline" label="Hủy quảng cáo" onPress={() => void mutate(async () => { const result = await cancelAdvertisement(id); setCancelConfirmVisible(false); return result; })} /></View></View></View></Modal></SafeAreaView>;
}
function Metric({ icon, label, value }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string }) { const { theme } = useTheme(); return <View style={[local.metric, { backgroundColor: theme.colors.surface, borderColor: theme.colors.border }]}><Ionicons color={theme.colors.primary} name={icon} size={20} /><Text style={[local.metricValue, { color: theme.colors.text }]}>{value}</Text><Text style={[local.metricLabel, { color: theme.colors.textMuted }]}>{label}</Text></View>; }
function Row({ label, value }: { label: string; value: string }) { const { theme } = useTheme(); return <View style={local.row}><Text style={[local.rowLabel, { color: theme.colors.textMuted }]}>{label}</Text><Text style={[local.rowValue, { color: theme.colors.text }]}>{value}</Text></View>; }
function Action({ danger, disabled, icon, label, onPress }: { danger?: boolean; disabled: boolean; icon: keyof typeof Ionicons.glyphMap; label: string; onPress: () => void }) { const { theme } = useTheme(); const color = danger ? theme.colors.danger : theme.colors.primary; return <Pressable disabled={disabled} onPress={onPress} style={[local.action, { borderColor: color }, disabled && { opacity: .5 }]}><Ionicons color={color} name={icon} size={19} /><Text style={{ color, fontWeight: "800" }}>{label}</Text></Pressable>; }
const local = StyleSheet.create({ action: { alignItems: "center", borderRadius: 12, borderWidth: 1, flexDirection: "row", gap: spacing.sm, justifyContent: "center", minHeight: 48, paddingHorizontal: spacing.md }, metric: { alignItems: "center", borderRadius: 14, borderWidth: 1, flex: 1, padding: spacing.md }, metricLabel: { fontSize: 10, marginTop: 2 }, metricValue: { fontSize: 18, fontWeight: "900", marginTop: spacing.xs }, row: { gap: 4 }, rowLabel: { fontSize: 11 }, rowValue: { fontSize: 14, fontWeight: "700", lineHeight: 20 } });
const createStyles = (colors: ThemeColors) => StyleSheet.create({ actions: { gap: spacing.sm }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: 16, borderWidth: 1, gap: spacing.md, padding: spacing.lg }, center: { alignItems: "center", backgroundColor: colors.background, flex: 1, justifyContent: "center" }, confirmActions: { gap: spacing.sm, marginTop: spacing.md }, confirmBackdrop: { backgroundColor: colors.overlay, flex: 1, justifyContent: "center", padding: spacing.lg }, confirmCard: { backgroundColor: colors.surface, borderColor: colors.borderSubtle, borderRadius: 16, borderWidth: 1, gap: spacing.sm, padding: spacing.lg }, confirmCopy: { color: colors.textMuted, fontSize: 14 }, content: { alignSelf: "center", gap: spacing.md, maxWidth: 720, padding: spacing.lg, width: "100%" }, header: { alignItems: "center", backgroundColor: colors.surface, borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: "row", gap: spacing.md, padding: spacing.md }, headerCopy: { flex: 1 }, hero: { backgroundColor: colors.primarySoft, borderColor: colors.primary, borderRadius: 18, borderWidth: 1, padding: spacing.lg }, heroFooter: { flexDirection: "row", justifyContent: "space-between", marginTop: spacing.sm }, heroLabel: { color: colors.textMuted, fontSize: 12 }, heroValue: { color: colors.primary, fontSize: 28, fontWeight: "900", marginVertical: spacing.sm }, icon: { alignItems: "center", height: 40, justifyContent: "center", width: 40 }, metricGrid: { flexDirection: "row", gap: spacing.sm }, muted: { color: colors.textMuted, fontSize: 11 }, progress: { backgroundColor: colors.primary, borderRadius: 3, height: 6 }, progressTrack: { backgroundColor: colors.surface, borderRadius: 3, height: 6, overflow: "hidden" }, screen: { backgroundColor: colors.background, flex: 1 }, subtitle: { color: colors.primary, fontSize: 12, fontWeight: "700" }, successNotice: { backgroundColor: colors.successSoft, borderColor: colors.success, borderRadius: 14, borderWidth: 1, gap: spacing.xs, padding: spacing.md }, successTitle: { color: colors.successText, fontSize: 15, fontWeight: "800" }, successCopy: { color: colors.text, fontSize: 13 }, title: { color: colors.text, fontSize: 20, fontWeight: "900" } });
