import type { AppTheme, ThemeColors } from "./types";
import { classicVisuals } from "./visuals";

const classicColors: ThemeColors = {
  avatarBorder: "#E4E6EB",
  background: "#F0F2F5",
  badge: "#168AAD",
  black: "#000000",
  border: "#D8DADF",
  borderRead: "#E4E6EB",
  borderSubtle: "#E4E6EB",
  card: "#FFFFFF",
  danger: "#D94B51",
  dangerContrast: "#FFFFFF",
  dangerSoft: "#F7E7E8",
  divider: "#E4E6EB",
  glow: "transparent",
  icon: "#65676B",
  input: "#F0F2F5",
  messageMine: "#E7F5F8",
  messageMineMuted: "#65676B",
  messageMineText: "#1C1E21",
  messageOther: "#FFFFFF",
  overlay: "rgba(0, 0, 0, 0.32)",
  placeholder: "#8A8D91",
  primary: "#168AAD",
  primaryContrast: "#FFFFFF",
  primaryPressed: "#117A99",
  primarySoft: "#E7F5F8",
  qrBackground: "#FFFFFF",
  qrForeground: "#111111",
  reaction: "#E7F5F8",
  reelBackground: "#000000",
  secondaryBackground: "#E9EDF2",
  shadow: "#000000",
  success: "#31A24C",
  successContrast: "#000000",
  successSoft: "#E8F5EC",
  successText: "#237A39",
  surface: "#FFFFFF",
  surfaceElevated: "#FFFFFF",
  tabBar: "#FFFFFF",
  tabBarBorder: "#E4E6EB",
  text: "#1C1E21",
  textMuted: "#65676B",
  toastBackground: "#FFFFFF",
  toastText: "#1C1E21",
  verified: "#168AAD",
  verifiedContrast: "#FFFFFF",
  visuals: classicVisuals,
  warning: "#B7791F",
  warningSoft: "#FFF4D6",
  white: "#FFFFFF",
};

// Video needs its own flat, high-contrast canvas. Reusing the light feed
// surfaces here makes white playback controls disappear on white circles.
const classicReelsColors: ThemeColors = {
  ...classicColors,
  avatarBorder: "#1877F2",
  background: "#000000",
  border: "#3E4042",
  borderRead: "#3E4042",
  borderSubtle: "#3E4042",
  card: "#242526",
  divider: "#3E4042",
  icon: "#FFFFFF",
  input: "#3A3B3C",
  messageMine: "#1877F2",
  messageMineMuted: "#D9E8FF",
  messageMineText: "#FFFFFF",
  messageOther: "#3A3B3C",
  placeholder: "#B0B3B8",
  primarySoft: "#263951",
  secondaryBackground: "#3A3B3C",
  surface: "#242526",
  surfaceElevated: "#3A3B3C",
  tabBar: "#242526",
  tabBarBorder: "#3E4042",
  text: "#FFFFFF",
  textMuted: "#B0B3B8",
  toastBackground: "#3A3B3C",
  toastText: "#FFFFFF",
};

const classicNotificationColors: ThemeColors = {
  ...classicColors,
  // Preserve a clear unread state against the white notification cards.
  surfaceElevated: "#E7F5F8",
};

export const classicTheme: AppTheme = {
  colors: classicColors,
  effects: {
    blurEnabled: false,
    cardRadius: 12,
    glassEnabled: false,
    glowEnabled: false,
    gradientEnabled: false,
    shadow: {
    elevation: 1,
      shadowColor: classicColors.shadow,
      shadowOffset: { height: 1, width: 0 },
      shadowOpacity: 0.06,
      shadowRadius: 2,
    },
  },
  gradients: {
    messageMine: [classicColors.messageMine, classicColors.messageMine],
    premiumBadge: [classicColors.primary, classicColors.primary],
    primary: [classicColors.primary, classicColors.primary],
  },
  isDark: false,
  mode: "classic",
  notifications: classicNotificationColors,
  reels: classicReelsColors,
  wallet: {
    accent: "#168AAD", accentContrast: "#FFFFFF", bannerAccent: "#168AAD",
    bannerBackground: "#E7F5F8", bannerBorder: "#CDE8EE", cardBackground: "#FFFFFF",
    cardBorder: "#E4E6EB", coinBackground: "#FFC94A", coinBorder: "#FFE79A",
    coinText: "#8A4B08", glow: "transparent", historyBackground: "#F0F2F5",
    iconBackground: "#E7F5F8", miniAccent: "#168AAD", miniBackground: "#F7F8FA",
    miniBorder: "#E4E6EB", miniSoft: "#E7F5F8", moreAccent: "#168AAD",
    moreBackground: "#F7F8FA", moreBorder: "#E4E6EB", moreSoft: "#E7F5F8",
    muted: "#65676B", skeleton: "#E4E6EB", text: "#1C1E21", walletBack: "#CDE8EE", walletBody: "#168AAD",
  },
};
