import type { AppTheme, ThemeColors } from "./types";
import { classicVisuals } from "./visuals";

const classicColors: ThemeColors = {
  avatarBorder: "#E4E6EB",
  background: "#E9EDF2",
  badge: "#3F6FA8",
  black: "#000000",
  border: "#C8D0D9",
  borderRead: "#DDE2E8",
  borderSubtle: "#DDE2E8",
  card: "#F7F8FA",
  danger: "#D94B51",
  dangerContrast: "#FFFFFF",
  dangerSoft: "#F7E7E8",
  divider: "#C8D0D9",
  glow: "transparent",
  icon: "#65676B",
  input: "#E9EDF2",
  messageMine: "#E2EBF5",
  messageMineMuted: "#626971",
  messageMineText: "#202327",
  messageOther: "#F7F8FA",
  overlay: "rgba(0, 0, 0, 0.32)",
  placeholder: "#8A8D91",
  primary: "#3F6FA8",
  primaryContrast: "#FFFFFF",
  primaryPressed: "#345F91",
  primarySoft: "#E2EBF5",
  qrBackground: "#FFFFFF",
  qrForeground: "#111111",
  reaction: "#E2EBF5",
  reelBackground: "#000000",
  secondaryBackground: "#DDE2E8",
  shadow: "#000000",
  success: "#31A24C",
  successContrast: "#000000",
  successSoft: "#E8F5EC",
  successText: "#237A39",
  surface: "#F7F8FA",
  surfaceElevated: "#F1F3F6",
  tabBar: "#F7F8FA",
  tabBarBorder: "#D3D9E0",
  text: "#202327",
  textMuted: "#626971",
  toastBackground: "#F7F8FA",
  toastText: "#202327",
  verified: "#3F6FA8",
  verifiedContrast: "#FFFFFF",
  visuals: classicVisuals,
  warning: "#B7791F",
  warningSoft: "#FFF4D6",
  white: "#FFFFFF",
};

// Video needs its own flat, high-contrast canvas. Reusing the light feed
// surfaces here makes white playback controls disappear on white circles.
const classicReelsColors: ThemeColors = {
  ...classicColors,
  avatarBorder: "#1877F2",
  background: "#000000",
  border: "#3E4042",
  borderRead: "#3E4042",
  borderSubtle: "#3E4042",
  card: "#242526",
  divider: "#3E4042",
  icon: "#FFFFFF",
  input: "#3A3B3C",
  messageMine: "#1877F2",
  messageMineMuted: "#D9E8FF",
  messageMineText: "#FFFFFF",
  messageOther: "#3A3B3C",
  placeholder: "#B0B3B8",
  primarySoft: "#263951",
  secondaryBackground: "#3A3B3C",
  surface: "#242526",
  surfaceElevated: "#3A3B3C",
  tabBar: "#242526",
  tabBarBorder: "#3E4042",
  text: "#FFFFFF",
  textMuted: "#B0B3B8",
  toastBackground: "#3A3B3C",
  toastText: "#FFFFFF",
};

const classicNotificationColors: ThemeColors = {
  ...classicColors,
  // Preserve a clear unread state against the white notification cards.
  surfaceElevated: "#E2EBF5",
};

export const classicTheme: AppTheme = {
  colors: classicColors,
  effects: {
    blurEnabled: false,
    cardRadius: 12,
    glassEnabled: false,
    glowEnabled: false,
    gradientEnabled: false,
    shadow: {
      elevation: 1,
      shadowColor: classicColors.shadow,
      shadowOffset: { height: 1, width: 0 },
      shadowOpacity: 0.08,
      shadowRadius: 2,
    },
  },
  gradients: {
    messageMine: [classicColors.messageMine, classicColors.messageMine],
    premiumBadge: [classicColors.primary, classicColors.primary],
    primary: [classicColors.primary, classicColors.primary],
  },
  isDark: false,
  mode: "classic",
  notifications: classicNotificationColors,
  reels: classicReelsColors,
  wallet: {
    accent: "#168BFF", accentContrast: "#FFFFFF", bannerAccent: "#00CDB8",
    bannerBackground: "#EEFFFA", bannerBorder: "#C9F2E9", cardBackground: "#F4FBFF",
    cardBorder: "#C7EAF9", coinBackground: "#FFC94A", coinBorder: "#FFE79A",
    coinText: "#B75C00", glow: "rgba(98, 231, 229, 0.22)", historyBackground: "rgba(255, 255, 255, 0.72)",
    iconBackground: "#E0F5FF", miniAccent: "#7C4DFF", miniBackground: "#FFF5FF",
    miniBorder: "#F0DDF5", miniSoft: "#EFE1FF", moreAccent: "#168BFF",
    moreBackground: "#F4FBFF", moreBorder: "#D8EDF7", moreSoft: "#DFF5FF",
    muted: "#71839C", skeleton: "#DCEFF8", text: "#07182D", walletBack: "#58DDF1", walletBody: "#168BFF",
  },
};
