export const layout = {
  desktopHeaderHeight: 64,
  chatSidebarWidth: 380,
  chatSettingsPanelWidth: 420,
  chatSettingsSubpageMaxWidth: 640,
  createGroupMaxWidth: 720,
  articleMaxWidth: 760,
  articleMediaMaxWidth: 720,
  feedMaxWidth: 720,
  notificationMaxWidth: 840,
  postDetailMaxWidth: 760,
  profileMaxWidth: 760,
  profilePostMaxWidth: 680,
  profileSubpageMaxWidth: 760,
  profileDesktopShellMaxWidth: 1920,
  profileFriendsSidebarWidth: 240,
  profileSettingsSidebarWidth: 320,
  reelsMaxWidth: 560,
  pageGutter: 24,
} as const;
