import assert from "node:assert/strict";
import test from "node:test";

import {
  parseGroupQrValue,
  parseProfileQrValue,
} from "../utils/qr-code.ts";

test("profile QR accepts the API share URL generated by the backend", () => {
  assert.equal(
    parseProfileQrValue(
      "https://api.mxh.ankt.vn/user/9cc0fa11-3c9a-48cc-a00a-ecfa2c2f05e1",
    ),
    "9cc0fa11-3c9a-48cc-a00a-ecfa2c2f05e1",
  );
});

test("profile QR accepts native profile links and rejects foreign hosts", () => {
  assert.equal(parseProfileQrValue("viora://profile/user-123"), "user-123");
  assert.equal(parseProfileQrValue("https://example.com/user/user-123"), null);
});

test("group QR accepts invite and fallback group links emitted by the app", () => {
  assert.deepEqual(
    parseGroupQrValue("viora://chat/group-preview?inviteCode=invite-123"),
    { inviteCode: "invite-123" },
  );
  assert.deepEqual(
    parseGroupQrValue(
      "viora://chat/group-preview?groupId=9cc0fa11-3c9a-48cc-a00a-ecfa2c2f05e1",
    ),
    { conversationId: "9cc0fa11-3c9a-48cc-a00a-ecfa2c2f05e1" },
  );
  assert.deepEqual(
    parseGroupQrValue("https://api.mxh.ankt.vn/group/invite-456"),
    { inviteCode: "invite-456" },
  );
});

test("group QR rejects unsupported links", () => {
  assert.equal(parseGroupQrValue("https://example.com/group/invite-456"), null);
});
